name: getlink
version: 1

handlers:
- url: /favicon.ico
  static_path: favicon.ico

- url: /main.css
  static_path: main.css

- url: /loading.gif
  static_path: loading.gif

- url: /default.png
  static_path: default.png

- url: /js
  static_dir: js
  
- url: /bootstrap
  static_dir: bootstrap